### ISSUE TITLE
Add Ability to Save File Open in Tab

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#1]
As a user of Postage, I'd like to work with script files in a more typical open/edit/save workflow so that I can create, edit and save scripts within Postage. I'd like to see a file-open button directly on the toolbar that lets me choose a file to open. When I edit the file, I should be able to save the changes to disk.

**Comment by justintocci** [comment]
Thank you for your suggestion. 

Currently, Postage allows you to install locally, and scripts are automatically saved in the ~/.postage directory. If you install Postage to a remote server, scripts are automatically saved in the remote ~/.postage directory which allows you to log in from any location and pick up right where you left off. This functionality is handled through the Postage binary.

However, we see the advantage of being able to point to a script locally and allow the browser to handle saving it without involving Postage. 

We've looked into the issue, we see [file api](http://caniuse.com/#search=file%20api) is a possible way to get this behavior.

We're wondering if you consider this behavior as replacing the current behavior or as a supplement? If the script sharing is not an advantage then we could reduce the Postage binary functionality and save a lot of code maintenance.

**Comment by anthonydb** [comment]
@justintocci Just my opinion, but the current behavior isn't entirely intuitive. I didn't realize that there was a ~/.postage directory where files are saved, and looking in it I see multiple folders with files from various sessions. If I were looking for something, it would be hard to find.

For myself, I like the ability to load a file, work on it and save it in a directory of my choosing. This is similar to pgAdmin and SQL Server Management Studio behavior. I would see this as a supplement to the current behavior if only for the ability to save on the server and have a colleague pick up on the same file -- but how do you handle conflicts? Other users may have a greater need for script sharing than I do -- I'm usually working solo.

**Comment by justintocci** [comment]
You are correct, the .postage folder isn't optimized for direct access. In the toolbar, navigate to "Tab", then "View All Closed Tabs". From there you can see the tabs you've closed for that user and database. They should be sorted such that the last tab closed is at the top. You can re-open a closed tab or download it.

I agree, the behavior you describe is more popular. 

It didn't happen often but I've lost work to other admin apps crashing over the years. The current behavior prevents scripts from being lost. It saves as you type. In the event of a sudden interruption, you log back in and start right where you left off.

Since the current behavior doesn't seem objectionable to you we're going to try to retain some of it while adding the new behavior.

This seems like a good time to revisit the 'history' button in the toolbar as well. I've always thought that code that is run successfully should be saved so you can look back at what you did. The current history button only saves the activity of the current session.

Regarding conflicts, at this time users will be notified if they try to overwrite the other person's work. It's a first write wins situation.

**Comment by michaeltocci** [comment]
I've checked the Javascript File API and it can't edit local files. I've done some research to see what the options are and everyone says to run a program to access the files through an HTTP server. That is what we're doing now so....

In the meantime, I want to point out that you can open a file into a tab from toolbar > Tab > Upload File To Tab and then download it when you're finished using the "Download As A File" Button to the left of the tab editor.

In the future, how could we close this issue? Do we need to make the .postage folder user navigable? Would we also want to be able to point to an arbitrary folder? 

If Anthony could elaborate what he feels we should do that would be very helpful. Maybe this whole issue was just due to a training issue. Maybe we need one of those 'first time user' tutorial walkthrough things where various tool tips appear on the screen?

**Comment by anthonydb** [comment]
My suggestions:
* Implement standard file open/save/close UI patterns:
** File > Open and File > Save icons.
** Ability to open a file dialog, search for a file, and load it into the editor. Change the wording away from "upload" to "open" and from "download" to "save," which are more common UI patterns.
** File auto-saves to its original location during editing.
** I can save the file when I desire.
 
I understand the reasons for the ~/.postage directory, but in practice it leads to a copy of a file in addition to my original. The upload/download paradigm feels like a lot of extra work compared to simple file open, edit and save.

**Comment by justintocci** [comment]
We want to implement the functionality you describe exactly. We agree it is superior in every way.

We haven't (yet) because Postage is a web server. We limit what Postage can access to a few folders for security reasons.

To implement the functionality you describe in a localhost situation, we would need to give a user the ability to work with any documents on their computer. 

But if one user starts Postage on say port 8080, and a second user on the same system goes to that port and logs in to a PostgreSQL server, then the second user would have access to the first user's files!

If we had a solution for that situation we could move forward. Anyone have any ideas?

**Comment by justintocci** [comment]
We've done several hours of research, had about four hours of meetings and talked to management. I'll sum everything up here but let me know if you want more detail.

We think the path of least resistance is to write a version of Postage in Electron. (If anyone has a better way please say something and we'll re-visit this.)

A whole new app is going to be a fair amount of work even though much code can be shared if we use something like Electron.

As of Sept. 2016, we have less than a hundred users. It makes sense to wait for more interest. Everyone that wants local file editing should speak up here. We'll leave this issue open for a while and see what happens. 

It may make sense to do this as a paid pro version. If there is interest in a paid version for this (or any other feature that becomes easier to do on top of Electron), please post a comment. If not, it's ok, we'll probably get to it in a free version at some point.

**Comment by justintocci** [comment]
We took a tour of PGAdmin4 today. One thing they had was the ability to save a file through a file dialog to anywhere on the local system. Possibly a desktop or a project folder. 

Right now we just have the download button which puts a file with a ".sql" extension in the downloads folder.

Michael, can we add the nicer file dialog to anywhere?

**Comment by michaeltocci** [comment]
No, I've looked and we can't pop open a nice save dialog.

**Comment by justintocci** [comment]
After further research we have a plan for an Electron version of Postage. 

Since an Electron version of Postage makes the PostageGUI versions redundant, we will freeze development on PostageGUI for Mac and Windows effective immediately.

We'll need to get an Electron version of Postage running first. Once that happens there are a handful of features we'll want to look at implementing through the Electron APIs:

Start and stop the Postage binary with an Electron window. Do we spin up a new Postage for each window?
Edit config files. On save, ask user if they want to re-start Postage to get the changes.

Once Electron has these features we'll be on par with the PostageGUI apps. At this point I think the PostageGUI apps can be dropped. Then we'll move on:

Open and Save dialogs.
Auto-save of files to local file system while editing. Yay!
Restart Postage binary on crash?

The rest of the Postage features should remain unchanged. Using Electron for the above features will prevent security issues and give a better overall experience for desktop users. 

The web version will still be preferable for some users and should remain unchanged. Progressive enhancement and all that. 

I think we should be able to keep it all to one code base. The changes should be limited.

**Comment by nunziotocci** [comment]
@anthonydb, @justintocci 

I have a simple electron wrapper done that allows you to edit configuration files.
Next what I am going to do is (only inside electron):

Replace upload with an open dialog.
While editing a file opened from the dialog, auto-save to the .postage directory.
Add a save button that saves the file to the original location (with Ctrl/Cmd + S as a shortcut)
If you hold down or right click on the save button give an option to "Save As..."

**Comment by justintocci** [comment]
Nice...

In the event of a crash all open tabs will have the latest changes saved and be there just as you left them when you log in again. They are still stored in .postage folder.

Plus, if you close the file without saving, the latest changes are still saved in the .postage folder and recoverable through the "View All Closed Tabs" function.

So we get all the functionality of PGAdmin, still maintain file system security and still maintain auto-save. I love it!!

**Comment by anthonydb** [comment]
@nunziotocci That sounds like a good combination. Look forward to checking it out!

**Comment by anthonydb** [comment]
Trying out the new file open/save functionality in the Electron version of the app on OS X. Bravo!

One suggestion: You've got the Open File command under the Tab menu. Then the Save and Save As ... commands are icons in the left bar. Whichever way you go, all three should be in the same place since they're all dealing with file open/save.

Otherwise, this is a great addition to Postage!

**Comment by nunziotocci** [comment]
@anthonydb 

We think we are going to copy the save/save as buttons into the tab menu instead of moving them.

Also, in case you didn't notice, we just made another release.

We had found out after the first Electron release, that because we had no menubar, we also had no copy/paste.
In this new release, we do have a menubar and copy/paste.

**Comment by nunziotocci** [comment]
@anthonydb 

I have copied the save/save as buttons to the Tab menu, this will be included in the next Saturday release.

**Comment by nunziotocci** [comment]
@anthonydb

Any comment on how we are doing this now?

**Comment by anthonydb** [comment]
Working great for me. Nice job!
