### ISSUE TITLE
Closed Tabs Search

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#117]
I know in envelope we have search functionality, can we add that to the closed tabs? I had to grep for a particular tab on my filesystem.

![screen shot 2017-02-22 at 3 57 42 pm](https://cloud.githubusercontent.com/assets/14278246/23273625/62fc1f84-f9c5-11e6-8eca-0e5b0606b49d.png)

**Comment by justintocci** [comment]
I'm thinking of how we could do this with minimum effort. 

What if we added a button to the Closed Tabs popup that opened a file browser window on the path where the Closed Tabs were stored? That would allow people to use their OS's search capabilities to find what they are looking for. Then they could just copy and paste it into a new tab?

Also, Nunzio said he might be able to easily add this functionality to the binary. @nunziotocci ?

**Comment by nunziotocci** [comment]
@justintocci I can add it to the binary, but then the code would be in two places (envelope and postage) because of the differences in APIs.

It would be really easy to just open the folder with [this module](https://github.com/sindresorhus/opn), in fact, we already use this module for opening external links.
I would need to test opening folders on Mac and Linux, but it works on Windows.

**Comment by justintocci** [comment]
Like I said, I'd be happy with a button that opened the folder. If someone re-opens the issue later that's fine, but I think that opening the folder would close this issue for now.

Would this work in Web Server mode?

**Comment by nunziotocci** [comment]
No, it wouldn't work in web server mode.
