### ISSUE TITLE
Export Workflow

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#12]
currently, the fields don't get double quoted automatically.

I have to put a comma separated list of columns in and then only those get quoted.

I'm torn. It should probably do something by column type. 

For now I think it would be better to just default the quoted fields list to "*" and have them all quoted. If someone has a strong opinion we could improve it from there.

**Comment by josephtocci** [comment]
I got asterisk working, and it defaults to asterisk. It didn't work before because it was wrapping the asterisk in parentheses when it shouldn't be. A column list needs the parentheses but not the asterisk as seen in the PostgreSQL COPY documentation:
https://www.postgresql.org/docs/9.2/static/sql-copy.html

It'll be in the next version.
