### ISSUE TITLE
Tools -> Server Settings hangs

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#132]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

I get the "Server Settings" popup, with the "Getting list..." graphic in the middle, but nothing is executed on the server and all three connections from postage->postgres remain idle, as confirmed by looking in e.g. pg_stat_activity

**Comment by justintocci** [comment]
stevenwinfield, I've been trying on and off to reproduce this error since you posted it and I'm having no luck. I hate to bother you on top of all the great help you've given us, but could you please send us your console output? That may help us reproduce the error. If you're using the desktop version of Postage, go to the VIEW menu and click "Toggle Developer Tools".

Thank you so much for all your help. The feedback you've given has really motivated the team.

I've posted an example:

![screen shot 2017-03-05 at 11 41 41 pm](https://cloud.githubusercontent.com/assets/14250339/23598045/4e3b0dcc-01fd-11e7-99ad-61741d6f3f17.JPG)

**Comment by stevenwinfield** [comment]
I'm struggling to reproduce it now, too!

It hung for me once today, but ever since first turned on the developer tools it now works fine - I that's probably more coincidence than anything else though.

I've tried to reproduce it by removing my .postage directory and starting postage again "fresh" but no joy.

Thanks for looking into this, though - I'll keep an eye out for it in future. And thanks for the heads up about developer tools.

FWIW here is the console output - the only error is due to me being behind a firewall.

![image](https://cloud.githubusercontent.com/assets/1327493/23609941/73d5cc0a-0268-11e7-9d3a-c09d89d5e61a.png)
