### ISSUE TITLE
Extra scrollbar appears when clicking on schema object

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#134]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

Before:
![image](https://cloud.githubusercontent.com/assets/1327493/23559857/4841ae36-0030-11e7-9024-666edea5afcd.png)

While holding left mouse button down over "public" in the left hand panel:
![image](https://cloud.githubusercontent.com/assets/1327493/23560091/18f0cf76-0031-11e7-83c5-0b480404e4f6.png)

...so most general clicking and browsing around schema objects causes the extra scrollbar to flash in and out of existence.

Cheers,
Steve.

**Comment by michaeltocci** [comment]
Fixed, will no longer be an issue in the next release.

The issue was in some code that allows you to drag an object name from the tree into a script. When you `mousedown` on the schema name, we add a helper element that shows what name you're dragging. This element did not have an initial position set and so it would go to the bottom of the screen and created the second scrollbar.

To fix this, I made the helper have an initial position that would not create a scrollbar.

Thanks for the feedback!
