### ISSUE TITLE
postage_port not obeyed

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#141]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

It seems the postage_port setting in postage.conf isn't being obeyed. 
I think instead that the postage_port file is written to my .postage directory the first time I run postage, and then there is no way to change it.

Trying to run a second instance of postage then fails with "Error - The port that postage was going to use is taken".

Some suggestions:
If a second instance of postage is run, perhaps it could be converted into the equivalent of File->New Window on the existing instance.
Alternatively, if postage_port is not specified in postage.conf, then get the OS to choose a free port for you by binding to port 0 - I assume that's what you do in the absence of an existing postage_port file and setting in postage.conf, in which case it might be as easy as cleaning up this file when postage is closing down.

We will have multiple users running postage on the same host, so at the moment there is also the potential for the port number that saved into the postage_port file to be the same for two users, and so they can never both run postage at the same time (without editing the file - which is probably a bit low level for your average user)

Cheers!

**Comment by nunziotocci** [comment]
Correct, the `postage_port ` file is used.
The reason is because Postage saves various things in cookies (login username for each conn, zoom level), and if we choose a random port every time Postage Launches those cookies are lost. I will research Electron session settings and figure out what I can do about this.

**Comment by nunziotocci** [comment]
I am not binding to port 0. I was unaware of that feature, but I wouldn't want to rely on it being present.
Instead I just create a new (random) `postage_port` file when it doesn't exist.

Also, I learned that postage uses localStorage instead of cookies for login usernames and the zoom level. That makes things a little different, but definitely possible.

If it comes down to it, I can just rename the localStorage files to have the right port in the name (I tested this manually and it worked).

**Comment by stevenwinfield** [comment]
Great, thanks.

[Here's a SO page](http://stackoverflow.com/questions/5895751/a-bind-with-a-port-of-zero-will-bind-you-to-a-free-port-is-this-portable) about the portability of using port 0 - TL;DR it's a BSD thing, so windows, linux, and mac should all support it.

**Comment by nunziotocci** [comment]
@stevenwinfield thanks for the link, I wonder why I hadn't heard of that.

I have made it so that when postage detects that the port previously chosen is currently in use, it picks a new one. I also made it so that renames the localStorage files when it does (this way, you keep your saved usernames).

Will be seen in the next release.

For now, if there are any conflicts, delete the `postage_port` file and a new one will be created when you launch Postage.
