### ISSUE TITLE
Group table-specific objects under their parent table

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#146]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

Currently, in the database browser panel, all indexes in a given schema are grouped together under the "Indexes" tree node.
It's not unusual for our schemas to have up to 50 tables in them, and I'm guessing other users have more, and each table has perhaps five indexes on it. This means that the list of indexes for a schema can grow pretty large, and it makes it difficult to answer the most common questions I find myself asking when looking at these objects is, which are:
- What indexes does this table already have?; And
- What indexes could I add that aren't too similar to existing indexes?

I think it would be very helpful if indexes for a given table were grouped under an "Indexes" tree node below the table's tree node.

I also see that you're not filtering out indexes that support a primary key or unique constraint - the drop/create scripts that are generated for these won't work.

As well as indexes perhaps other table-specific objects, such as constraints, triggers, and rules, could also be grouped under their parent table.

**Comment by justintocci** [comment]
Yes, the independent Indexes node. We tried it. It didn't really work well. We will remove it.

Probably the reason we haven't is just that we haven't figured out what we want to do. Indexes do appear within the individual table scripts. Also the other objects you mention.

We've been reluctant to add all those objects as nodes because then we'd have a bunch of nodes. We've been trying to keep the object tree shallow. PGAdmin's tree was always a pain because it would get deep quickly.

I've spoken with the team and we're going to add all the nodes. We just don't know what else to do. Hopefully, the object tree will remain better than others.

**Comment by crosstocci** [comment]
The table and view specific objects will be grouped under their parent tables in the next release
