### ISSUE TITLE
New SQL tabs start with 10 blank lines

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#148]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

I'm curious - why is this?
It means that if I open a new tab, cut some text from another application, then click on postage again to give it focus, I will (more often than not) end up pasting my SQL on line 10.

Obviously this isn't a huge problem, just a little quirky.

Thanks.

**Comment by justintocci** [comment]
Try not to click in the white space on the tab before you paste. Then you'll paste into line one.

The reason we start with ten lines is just so that you don't get to the end of a document and have the last line directly on the green bar. 

If you feel strongly about it we'll remove it. Let us know.

**Comment by stevenwinfield** [comment]
I don't feel too strongly about it, it's just not obvious that it was intentional.

Cheers!
