### ISSUE TITLE
Activity Stats - rolling window

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#152]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

I really like the activity stats graphs, but after they have been open for a while they contain a lot of data, which blurs into a bit of a mess.

![image](https://cloud.githubusercontent.com/assets/1327493/23752573/cf58e2e4-04cd-11e7-91ce-e6597955f9eb.png)

If some issue is reported to us about the database, such as query slowness, it would be great to refer to these graphs to look at recent history. Of course, they must be open all the time since we don't know when something might happen.

So I think it would be great if there was a user-definable window size so that only data from, say, the last hour is shown (and the rest can be forgotten about).
It would also help if the tick markers were actual times, rather than number of seconds since collection started.

What are the units of the graphs, by the way? I'm guessing that the one marked "transaction" is in transactions per second, but this isn't explicitly mentioned anywhere. Can the sampling rate be made user-definable too?

**Comment by justintocci** [comment]
I hesitate to turn Postage into a full blown performance tool, especially since we have a short list of apps we want to write and a major feature of one is that it records and aggregates performance data for PostgreSQL. However, these features seem harmless to me.

1) Switch units to time of day. The time zone could be local time or PostgreSQL time. Do whatever is easiest at first and we'll switch it later if someone asks.

2) "Discard data older than X" should be at the top of the screen. Default it to one hour (in seconds) and let the user change it. Set the charts to discard data points older than the interval.

3) Sample rate should be integrated into each chart label. For example, "Tuples per X seconds". This way people can set them individually. Default to one second. No data is discarded on a change. (By labelling the charts with time of day the sample rate won't invalidate previous data)

4) Add "Collect statistics every X seconds" to the top of the screen. Default to one second. Have it set all the individual charts when it gets changed. No data is discarded on a change.

I think this covers everything. Steve, let me know if I missed anything.

**Comment by stevenwinfield** [comment]
Nope, that all sounds fantastic.
Thanks!

**Comment by nunziotocci** [comment]
Will be seen in next release.
