### ISSUE TITLE
(Optionally?) use a fixed-width font for query results

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#155]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

I find it helps when visually diffing values in adjacent rows.

**Comment by justintocci** [comment]
We use local storage to save options from session to session. I want to expand that a bit. Here's what we're going to do.

1) Add a button to the Tools menu for "Postage Options". This should lead to a popup.

2) Expose the current options in the popup so people can adjust them. I don't know what these even are so this would help me too.

3) Add an option to set the CSS for results. You should easily be able to toggle between our normal and monospace results with no CSS knowledge.

4) Users consistently ask for features we already have when they are presented with the unlabelled buttons. But, although there are strong reasons that Postage should ship with labels on all the buttons, I already miss the small buttons.  Users need a way to toggle from "Labeled Buttons" to "Unlabeled Buttons".

5) Make it so that when the Popup is closed, all the option changes will be put into effect.

**Comment by michaeltocci** [comment]
To make the preferences easier to find, my opinion is that we should have a "Preferences" button under the "User" dropdown and a "Postage Options" button under the "Tools" dropdown.

**To whomever implements this,**

Right now, the only preferences are:
- Copy format preferences (other.js: lines (approx) 100, 101, 133)
- Zoom level (zoom.js: lines (approx) 50, 87)
- Sidebar width (other.js: lines (approx) 1713, 1727, 1731)

Each preference has it's own property under `localStorage`. The new properties should be:
- `localStorage.resultsFont = ` `'monospace'` or `'proportional'` (default to `'monospace'`)
- `localStorage.labeledButtons = ` `'false'` or `'true'` (default to `'true'`)

When creating the CSS for the monospace result mode, look at Ace editor's font CSS. Their CSS already tries to give the best monospace font available.

**Comment by justintocci** [comment]
instead of resultsFont, call it customCSS and we'll load it into a style element at the top of each document. They'll need a way to edit the customCSS in an ACE editor. Also, we should leave a warning that local storage can be cleared out, so they may want to save a copy somewhere.

I like all the others.

**Comment by crosstocci** [comment]
The Labeled buttons option has been added.

**Comment by josephtocci** [comment]
I have added the other preferences but I haven't added the custom css yet.

**Comment by crosstocci** [comment]
The customCSS property of localStorage can now be edited in: Tools> Postage options.

This will update the CSS in all postage pages except config.html.

I am assigning @nunziotocci to adding this to config.html.

**Comment by josephtocci** [comment]
Make sure to default the custom css to:
```
.sql-results-area {
    font-family: "Monaco","Menlo","Ubuntu Mono","Consolas","source-code-pro",monospace;
    font-feature-settings: normal;
    font-kerning: auto;
    font-language-override: normal;
    font-size: 11.2px;
    font-size-adjust: none;
    font-stretch: normal;
    font-style: normal;
    font-synthesis: weight style;
    font-variant: normal;
    font-variant-alternates: normal;
    font-variant-caps: normal;
    font-variant-east-asian: normal;
    font-variant-ligatures: normal;
    font-variant-numeric: normal;
    font-variant-position: normal;
    font-weight: 400;
}
```

**Comment by nunziotocci** [comment]
@crosstocci, the unlabeled buttons only work on SQL tabs, not the object tree scripts.

**Comment by justintocci** [comment]
correct. We'll let someone ask if they need it for the other tabs. the other tabs are less used so the labels are more useful.

**Comment by josephtocci** [comment]
I have the explain buttons in a drop down, but only for the labeled buttons. We don't need a drop down for the unlabeled buttons.

**Comment by crosstocci** [comment]
@justintocci, do you think that defaulting to the monospace CSS is a good idea, or would it be better if we default to a comment with  the monospace CSS  in it?

**Comment by justintocci** [comment]
I'll leave it to you.

**Comment by josephtocci** [comment]
I made ti default to what we currently have, but in the ace editor you can uncomment the Monospace css and you will have Monospace results.
