### ISSUE TITLE
Postage logs me out after a period of inactivity?

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#157]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

I might be wrong, but it seems that if I check a postage window that has been open, and logged in, for a few hours then it returns to the login screen.

If so, is there any way to disable this, or adjust the timeout?

Thanks.

**Comment by josephtocci** [comment]
stevenwinfield,

The postage.conf has a login_timeout setting for the number of seconds to log someone out, it defaults to one hour. So if you don't do anything in postage for an hour, you get logged out.

I think there are two things we need to do,

1:
Modify the default postage settings file to have comments explain every configuration settings. Use the postgresql configuration file for an example. Right now the postage and workflowproducts/envelope project has very poor configuration files.

2:
When someone doesn't use postage for longer then the timeout, just sending them to the login page is not enough. We should send them to the login page and have the login page display a message saying that you were logged out because in inactivity.

To do this:
send something like ?timeout=true or ?timeout=current_datetime in the arguments for the login page, then have the login page display a message when the timeout parameter is set in the url.

**Comment by stevenwinfield** [comment]
Ah - I see, thanks.

A few extra points:

login_timeout is commented out in my postage.conf - I would have thought that that meant there is no timeout set.

I agree that more documentation in this config file would be good, and it should include the default values, and the units ("login_timout = 30" is obviously minutes, but it would be nice to know that explicitly.

The comment at the top of postage.conf recommends referring to the man page.
Whether or not more documentation is added to this config, I think it would be nice to have access to the man page in the desktop app.

**Comment by josephtocci** [comment]
stevenwinfield,

The login_timeout unit is seconds, having login_timeout = 30 is deceiving, because it's not minutes, it's seconds. Really the whole default config file needs to be rewritten. Hence item no 1 above.

Also, the man page is generated from a markdown file, we can generate an html document from the markdown file and add that as a page to the electron app. This would also be useful.

3:
Generate html from our markdown files and add them to the electron app.

**Comment by stevenwinfield** [comment]
Whoa, yes - having the config suggest 30 as a sane value for login_timeout is definitely misleading!
Having access to an HTML version of the man page will be really helpful - thanks.

**Comment by josephtocci** [comment]
1. Done
I have rewritten the default config file.

2. Done
I have added the error message to the timeout. I am currently clearing out some valgrind errors from adding the error message.

3.
We still have to generate html from our markdown files.

**Comment by josephtocci** [comment]
I have created the html file, Nunzio is goes to add the html file to the electron app.

**Comment by josephtocci** [comment]
Nunzio and I added a link to the postage html file from the configuration screen. Will be seen in the next release.
