### ISSUE TITLE
Building on OS X El Capitan with Xcode 8 installed

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#16]
When I compiled postage with Xcode 8 and then started postage, I got this error:

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/jtocci/Repos/postage/postage_electron/./postage (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/jtocci/Repos/postage/postage_electron/./postage (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

It looks like clang defaults to the latest OS regardless of the current OS version.

**Comment by nunziotocci** [comment]
This was caused by you having Xcode 8 installed.

In macOS Sierra, clock_getttime was added, and my configure check for it was succeeding.
But, you still had OS X El Capitan installed, so it crashed at runtime.

Now in the configure script, I detect this and emit a warning and ignore the presence of clock_gettime.
