### ISSUE TITLE
Autocomplete on a nonexistent object produces a database error in the log

### ISSUE THREAD

**Issue by clomdd** [workflowproducts/postage#163]
Hi,

If I type bob.trade into a sql tab, I get an error generated into the database log:
error_message='schema "bob" does not exist', sqlstate_code='3F000', user_query="SELECT * FROM (\nSELECT '', $notTObeMATCHEDtoken$bob.bob$notTObeMATCHEDtoken$::regclass::oid\n) em;"

This is before I have hit run, so is a result of the autocomplete trying to find the schema....

Thanks,
Chloe

**Comment by michaeltocci** [comment]
Thanks for letting us know!

@crosstocci here's what you need to do.

First, to fix the schema error, use the object tree's list of schemas and only run the autocomplete if the schema name is in that list.

Second, you need to track down why instead of searching for `bob.trade` the autocomplete is searching for `bob.bob`. I believe the issue is either in the `autocompleteGetPrefix` function or in `autocomplete-logic.js` at about line 1006.

**Comment by crosstocci** [comment]
I have changed that code to only run when that schema object is in the shown objects list.
I could not however reproduce the problem where it sends ```bob.bob```.

**Comment by justintocci** [comment]
@clomdd Is it possible that you typed bob.bob and then backspaced and typed bob.trade? We're having trouble reproducing the error.

**Comment by clomdd** [comment]
Thanks for the speedy fix! I think it is entirely possible that I sent you the wrong error associated with the command, apologies for that. I was hurrying to get things finished before a few days away from the office.

**Comment by michaeltocci** [comment]
No worries, thanks for the update!
