### ISSUE TITLE
CONSTRAINT CHECK items are showing up twice.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#17]
I've got a check constraint and it shows up twice.

i drop it and they both go away.

I add it back and they both come back.

to duplicate:
ALTER TABLE usr.rinv ADD CONSTRAINT rinv_ttype
    CHECK (ttype::text = 'ROCKET'::text OR ttype::text = 'HANDLING CHARGE'::text OR ttype::text = 'RECARO'::text OR ttype::text = 'ON BAG'::text OR ttype::text = 'RETURN'::text)

Looks like this:
...
  ttype character varying(20) NOT NULL,
  expires date,
  CONSTRAINT rinv_pk PRIMARY KEY (id),
  CONSTRAINT rinv_ttype CHECK (ttype::text = 'ROCKET'::text OR ttype::text = 'HANDLING CHARGE'::text OR ttype::text = 'RECARO'::text OR ttype::text = 'ON BAG'::text OR ttype::text = 'RETURN'::text),
  CONSTRAINT rinv_ttype CHECK (ttype::text = 'ROCKET'::text OR ttype::text = 'HANDLING CHARGE'::text OR ttype::text = 'RECARO'::text OR ttype::text = 'ON BAG'::text OR ttype::text = 'RETURN'::text)
) WITH (
  OIDS=FALSE
);

**Comment by michaeltocci** [comment]
Before:
![before](https://cloud.githubusercontent.com/assets/10438221/19130725/1b7549e6-8b12-11e6-9b8b-fd9a3c22b8b3.png)

After:
![after](https://cloud.githubusercontent.com/assets/10438221/19130695/f07c9258-8b11-11e6-8f1d-d6687c2032d4.png)

The fix will be in the next release.

There were two sections in the table generation code:
1) non-CHECK CONSTRAINTs
2) CHECK CONSTRAINTs

The issue was that the "non-CHECK CONSTRAINTs" section didn't actually exclude CHECK CONSTRAINTs.

To fix this I removed the "CHECK CONSTRAINTs" section and renamed the "non-CHECK CONSTRAINTs" section to "CONSTRAINTs".
