### ISSUE TITLE
Potential support for job scheduler

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#173]
Hey all, I want to start by saying I really appreciate the work that has gone into postage.  It's a great piece of software, and I really hope more people start using it.  It deserves more mindshare compared to the alternative.

I wanted to see if there was any interest in adding support for job schedule management within postage?  I'm the author of [jpgAgent](https://github.com/GoSimpleLLC/jpgAgent) which is a pgAgent compatible scheduler with a ton of extra features.  Now there is already a UI for pgAgent (and by proxy jpgAgent) in pgAdmin 3/4, so I don't know if that's something you want to spend time on...  

I've also been working on a total re-write called [pgAutomator ](https://github.com/Tostino/pgAutomator)that is not tied the the pgAgent schema in any way, and has even more features.  If you've ever used SQL Server Agent, it's very close to that in functionality.  Pretty much, I have it mostly working and my next step was to build a UI for managing it, but I have been way short on time to do that well, and UI work is really not something i'm great at anyways.  I thought that if there was interest from you guys in supporting the UI in postage, I could dedicate some time to putting the finishing touches on the project and packaging it as an extension, creating installers for the agent, etc.

Everything with pgAutomator is supposed to be done through a function.  There should be no need at all for arbitrary SQL to manage anything with it, so that should make it's use much easier.  If interested, the schema and functions for it are defined [here](https://github.com/Tostino/pgAutomator/blob/master/src/main/resources/pgAutomator.sql). 

If there is any interest, great! I'd love to work with you all on it.  If not, that's fine too.  I'll free up a little some time and be able to write a management application on my own eventually.

**Comment by justintocci** [comment]
First off, we respect that you're giving back to the PostgreSQL community. We in the PostgreSQL community are sorely in need of people that are willing to compete in the PostgreSQL ecosystem by contributing time and talent to make great tools. Thank you. 

Regarding Postage, while we are not averse to adding any functionality to Postage, we have no plans to extend it into Agent functionality at this time. 

I ended up writing a long offer to help but decided to send it to you directly. Regardless of how that turns out, I wish you the best of luck.

Since we don't plan to add Agent functionality to Postage I'm going to close this issue.
