### ISSUE TITLE
explain.depesz.com text Explain

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#176]
Check out the explain.depesz.com text Explain. It's pretty cool. Maybe we should look at copying some of this for our text explain output.

**Comment by stevenwinfield** [comment]
[PEV](http://tatiyants.com/pev) is even better IMHO, and by the author's own admission is heavily influenced by explain.depesz.com - his blog post about plan visualisation is helpful in any case:
[http://tatiyants.com/postgres-query-plan-visualization/](http://tatiyants.com/postgres-query-plan-visualization/)

**Comment by Tostino** [comment]
@stevenwinfield I've used both, and while the one you listed is not bad for a simple query, with a more complicated query plan it quickly gets out of hand and for me becomes totally unusable. For my use case, I find it exceedingly rare that I need to use tools like that for simple queries.

Not that explain.depesz.com is the perfect plan anaylzer, but personally I find it better than all graphical alternatives when trying to pinpoint a performance issue.

**Comment by Tostino** [comment]
Another note, is being able to easily make the explain plan (in all ways you want to visualize it be it text, html, or graphical) expand to your your whole screen (probably in a separate window so it's usable on multiple monitors) is very helpful.  Most tools like pgAdmin or SSMS like to lock it in that same little area at the bottom of the screen in a tab next to your query results.  Then you have un-dock that pane from the main window and awkwardly resize it manually by dragging each corner.  It's not impossible to do, but it's awkward with the tools i've used most in the past.

**Comment by michaeltocci** [comment]
Taking into account everyone's suggestions:

It sounds like we want two explain buttons (explain and run and explain without run), but we want the explain window to be a new page. When the explain is first opened, it'll be in the results pane and have a button to open a new window.

Having a new window is definitely what we want because then the user can use their OS fullscreen/split-screen functionality. To put the initial results in the results pane, we'd just need to use an HTML `iframe` element.

The new window would have all 4 display types:
- Graphical (based on PEV)
- HTML (based on depesz)
- TEXT (based on depesz)
- STATS (based on depesz)

Each type would be accessible from a tab control at the top of the page. This would give us both the PEV and explain.depesz.com display modes.

Thoughts?

**Comment by nunziotocci** [comment]
Will be seen in next release/
