### ISSUE TITLE
Compiling Source Code Guide for Windows?

### ISSUE THREAD

**Issue by Vonatzki** [workflowproducts/postage#189]
I am not quite sure if this is the right avenue for this. We are planning to host Postage on a server thus we need the web server mode capability of the app. As mentioned in README.md, I have to compile the source code releases.

However, README.md does not detail how to compile the source code exactly (this might be due to being common knowledge for non-beginners here). I am not exactly sure how to proceed once I downloaded the source code zip file.

Hope you can help me, a simple link to a tutorial would suffice, thanks!

**Comment by josephtocci** [comment]
No problem, post any questions you have in github. We're always around.

This is the document you are looking for:
https://github.com/workflowproducts/postage/blob/master/INSTALL_WEB_SERVER_MODE.md

**Comment by Vonatzki** [comment]
Hey there, I'm commenting here to avoid redundancy of issues:

I am still having difficulties setting up a web server using the source code release. I am currently using Windows 7 x64 PC. I am not sure if these steps as stated in INSTALL_WEB_SERVER_MODE.md is applicable to my OS:

```
    cd postage
    ./configure
    make
    sudo make install
```

Browsing through the files, I noticed there is a .bat file named package-windows. I tried running this and it seems (correct me if I'm wrong) this is the one intended for those who'd like to compile Postage using Windows. However, I'm encountering a few [errors](https://github.com/workflowproducts/postage/files/1070408/package-windows-result.txt) when running this.

I hope you can shine light for Windows users like me on how to set Postage as a web server. I only have basic knowledge when it comes to this. Thanks!

**Comment by crosstocci** [comment]
@Vonatzki we use Visual studio 2017 to compile postage on windows but our Visual studio guy is out of town right now, if you have experience with visual studio then you might be able to use that. We are doing our best to get this figured out as soon as possible, but it may take a day or two.

The package-windows file is used by the postage team for compiling postage with electron, it does not compile the web server version.

We'll let you know if we find more information.

**Comment by justintocci** [comment]
@Vonatzki 
I'm filling in for Nunzio today and I have a solution for you.

Install the Electron version of Postage and then navigate to this folder:

C:\Program Files (x86)\Workflow Products\Postage\resources\app\postage

The web server version will be in this folder. It's called "postage.exe". We ship that with every Electron install and it's the same thing you would get if we had a separate, non-Electron distribution. 

That's it! You should be good to go with your server install!

### I have added a new README for this type of setup:

https://github.com/workflowproducts/postage/blob/master/INSTALL_WEB_SERVER_MODE_WIN.md

Please read the that and the man pages for instructions on command line arguments and setup. Feel free to open a new issue if you have trouble with setup. Suggestions to improve our documentation are always welcome.

### IF YOU WISH to compile Postage yourself on Windows then you'll need Visual Studio 2017. If you need to tackle that please open a new issue and let us know where you've gotten stuck.

### IF YOU WANT us to do a non-Electron distribution of Postage with a Windows Service module and the whole deal please open a new issue and we'll have Nunzio work on that when he gets back next month. We have all that for Envelope, which is a sister project that shares a lot of code so that would be very doable. We just don't have a lot of resources so we often don't do stuff like that until someone asks.

# thank you for taking the time to file an issue! Please re-open this issue immediately if we failed to address your problem fully. Thanks again.

**Comment by Vonatzki** [comment]
Wow! This is a big help! I can now run in web server mode! Thank you so much!
