### ISSUE TITLE
Autocomplete: eliminate having to type 'public' or `pg_catalog` to see list of tables 

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#236]
It would be helpful for autocomplete to let me get to a list of table names faster. Currently, in the Postage editor, if I type `SELECT * FROM`, I next have to type a `p` and choose `public` or `pg_catalog`, then add a dot `.` to access an autocomplete list of table names.

Is it possible to eliminate the need to select either of the `p` choices and let me get to a list of tables right away?

**Comment by justintocci** [comment]
Anthony is right. Since it would be valid to type table names without schemas if they are in the current path, it makes sense for us to show them.

So whereas right now, autocomplete on the first letter shows the schema, instead it should show all the schemas and any tables that are in the path. Seems like an easy fix.

**Comment by crosstocci** [comment]
Fixed in next release.
