### ISSUE TITLE
Maybe we should get into Apple and Windows App stores?

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#26]
I'd like to hear from the community about this since it would mean a significant investment of resources.

At this time, the only benefit would be getting past the "you attempted to open a program from an unidentified developer" warnings. That's not to say this is not a good reason to do it. I just don't know.

**Comment by anthonydb** [comment]
The LOE behind getting into those stores (passing their various reviews and requirements) is worth looking into. You'll need to decide whether it's worth the opportunity cost given that you've got a smaller team.

**Comment by nunziotocci** [comment]
electron-builder has targets for both the Mac and Windows app stores, so it wouldn't be particularly difficult to do.
Although, this would require $99 a year for the Mac App Store, and $99 one time for the Windows Store.

Other notes regarding Windows:
Unfortunately, we would only be able to support Windows 10 "Anniversary" and later, but this isn't really a problem either, because the Windows Store is only available on Windows 10, and the "Anniversary" update is free for all installs of Windows 10.
So, we would still have to have a Windows Postage download for Windows machines that don't have Windows 10 "Anniversary" installed.

Also on the Mac front, we could continue to distribute a DMG in addition to the App Store, but the apps would be signed so Gatekeeper would allow them through.

**Comment by justintocci** [comment]
Well, I estimate our hard costs of Postage to be well into six figure territory by now (we're going on like eight years of development!) so I don't think a hundred bucks here and there is an issue. 

What I am concerned about is our weekly release schedule. If this is going to slow things down then I want people to demand it before we commit to it. If this turns into an Electron situation where it actually saves us time then full speed ahead. 

We should table this for a week or two and get production releases out. Then come back to this and maybe give one of these stores a try.

**Comment by nunziotocci** [comment]
If we get on the app stores, users will be notified of updates.

But, Electron has made it much easier to install Postage, so I will close this for now. If the community expresses interest in this, we will look into it.

**Comment by michaeltocci** [comment]
Someone have expressed a desire for us to get the code signed.

Here's a link with info on how to sign a program: http://wiki.lazarus.freepascal.org/Code_Signing_for_Mac_OS_X#Using_codesign_to_sign_your_executable

We need to get an Apple Developer account so that we can use the DeveloperID to sign the code.

**Comment by nunziotocci** [comment]
We have code-signed releases now, and we have decided against going on the Mac App Store.
