### ISSUE TITLE
Statically compile on Windows.

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#27]
The Universal CRT for Windows is not installed by default on 7, 8 and 8.1, so we need to statically compile LibreSSL, libpq and postage itself statically to support those platforms.

**Comment by justintocci** [comment]
Since fully patched versions of Windows 7, 8 and 8.1 do not have this problem, I am closing this. Best practice would be to only run fully patched versions of these OS's anyway.

If the community puts forth a reason why we need to do this then let them re-open it and we'll consider putting this back on our to do list.
