### ISSUE TITLE
Datasheet doesn't show partial characters

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#273]
This could be windows specific, but if a character doesn't fit, even by only a few pixels, it doesn't display at all:
![capture](https://cloud.githubusercontent.com/assets/7560749/26522553/f261b138-42c8-11e7-9215-50385e1f064f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7560749/26522552/f2606558-42c8-11e7-9f96-3377b6503226.PNG)

**Comment by justintocci** [comment]
This is causing people to believe the field is being shown completely when it is not. 

The expected behavior would be for the text to go right to the border and get cut off. This would prevent anyone from thinking all the data is shown when it is not.

Alternatively, we could have some kind of indicator that the data did not fit. I do not want three dots (...) because it takes up too much room and is generally annoying.
