### ISSUE TITLE
New Datasheet column width

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#288]
Oh look, a small column of data, but it looks like a little bit of data is hidden,
![screen shot 2017-05-31 at 10 16 38 am](https://cloud.githubusercontent.com/assets/14278246/26645371/6b9bdd58-45fd-11e7-9655-2def23492d72.png)

So lets double click on the edge of the column to smart resize. 
![screen shot 2017-05-31 at 10 16 54 am](https://cloud.githubusercontent.com/assets/14278246/26645394/7dd27b08-45fd-11e7-91b4-ad2af103d5ed.png)

Whoa, that's alot of data, why doesn't the columns automatically resize to an intelligent size, it seems like we use the size of the column name to determine size, (not in image) but we should be using the data.

**Comment by justintocci** [comment]
this is correct behavior. you don't want the columns to be super wide on load, it gets tiresome. we set the initial size by the column name or a default size. then you re-size just the columns you're interested in that happen to need more data.

let me know if you still have questions or a situation i didn't cover

**Comment by josephtocci** [comment]
I understand what you are saying, but I only had one column, and a ton of wasted space with no columns. If there are only a few columns that by default don't cover the full width of the view, then use the default sizes, increase the size while maintaining the ratio's until the whole datasheet is covered in data, then stop increasing the size.

Point is, I shouldn't have to resize the only column so that there is no wasted space in the datasheet.

**Comment by justintocci** [comment]
Ok, i can sort of agree with that.  The problem with your strategy is that if the three columns all have a full screen's width of data, then it'll fill most of the screen with the first one and the next two will either be small (to make them fit on the screen) or so large that you'll need to scroll to see them.

If they are too large and you must scroll to see them then you're way worse off than having to make them bigger because at least you don't have to scroll first.

This may be too difficult to be worth it, but... How would you feel if it attempted to put down the first row, then if it didn't fill the viewport it could calculate the unused width and split it up between all the columns?

I can't say I'm excited by it because then very small values in a single column result will look funny. But it would solve your problem and not make problems for at the same time.

**Comment by josephtocci** [comment]
Actually that is what I was suggesting, but you explained it better. Take the unused space and divy it up with correct ratios to the columns.

Here's another option, take the average width of the data in the column and use that **but only if it is shorter then what we were going to do**, however that could be slow.

Another option is to use the types themselves to determine start sizes. For instance, dates need only a specific width, unless the column name itself is longer than a date.

@michaeltocci can you weigh in.

**Comment by justintocci** [comment]
What you're saying about Dates makes a lot of sense. 

At this time I don't know what to do. We need a plan that makes sense for all situations and I just don't know how we can improve on what we have without making some situations worse. If we don't have a plan soon I'm going to close this issue.

**Comment by nunziotocci** [comment]
Since it's been a month and we don't have a plan, I'm closing this issue. If somebody wants this, please reopen.
