### ISSUE TITLE
Object search functionality

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#301]
One of the features I use all the time in PGAdmin is the object search functionality.  It lets me search for a string within objects (table names, column names, comments, functions, views, etc).  It also lets me specify the objects I wish to search within (or all), and limit to specific schemas (or all), etc.

I could not find any similar functionality within Postage.

**Comment by justintocci** [comment]
What I do is I click on the schema and then above the scripts, click the button "Dump schema to script". You'll then get a list of item types that you'd like to output. I usually choose FUNCTIONs, trigger FUNCTIONs and VIEWs, though sometimes I also check off TABLEs depending on why I'm searching.

Now click "open script" at the bottom and you'll get one script with all your stuff that you want to search. Click CTRL-F to get the find popup and you should be good to go.

We went this route to make it so you can have a good script to run once you found the items you were looking for instead of having to pick things out one by one.

Let us know what you think. If this works for you let us know so we can close this issue.

**Comment by justintocci** [comment]
@Tostino I went to use this functionality today and there was an error. It's been fixed in 3.2.15 so I guess wait until then to try it out if you're using the Electron version.

**Comment by Tostino** [comment]
@justintocci Alright will do.

**Comment by justintocci** [comment]
This is fixed. We'll have a new release out in a day or two and you can try it.
