### ISSUE TITLE
Transactions not intuitive

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#302]
I am having a hard time knowing when a transaction is held open or not in Postage, as opposed to PGAdmin.  In PGAdmin, if I issue a BEGIN I have a button which will now be enabled which allows me to either commit or roll back indicating I have a transaction open.  I can then run any queries, and that transaction will not close unless I manually issue a COMMIT, ROLLBACK, or click either of the corresponding buttons in the tool bar.

I am having a bit of trouble with that workflow in Postage, as I don't have any indication that a transaction is open or not.

Also, autocommit seems to work quite strange compared to what I would expect.  Normally, if autocommit is enabled, a transaction would commit at the end if the user hadn't specified an explicit BEGIN; at the start of the query.  If that explicit BEGIN was there, I would expect it to leave it to the user to issue a COMMIT or ROLLBACK.

Sorry for the flood of issues tonight, I just have been trying to use Postage more as a full replacement for PGAdmin, and in doing my day-to-day tasks this is what i've noticed so far.

**Comment by justintocci** [comment]
We appreciate every issue people file so keep them coming, don't hold back.

Postage's normal operation involves putting a BEGIN before your script and an END at the end. This way, all your queries run at once or get rolled back (normal caveats apply). 

My understanding of Autocommit is that rather than running your script (or selection) in a single transaction, each individual SQL query is run in it's own transaction. This way all queries either complete or fail.

To my knowledge, we've never tried to allow a transaction to span over more than one 'run' command. Give me a couple days to research this as our C programmer is out of state right now. I'll get back to you shortly.

**Comment by justintocci** [comment]
Ok, with Autocommit OFF (default):
you can't have a transaction span more than one 'run'. With autocomplete off, Postage sends a BEGIN at the beginning and a COMMIT at the end of every click of the 'run' button. Since PostgreSQL doesn't support nested transactions, you can't have a transaction not be committed when it completes.

with Autocommit ON:
Postage does not issue BEGIN or COMMIT statements at all. In that case, you can do what you want, even have a transaction left open when it completes a 'run'.

**Comment by justintocci** [comment]
TODO: If a transaction is left open, we need to give some kind of feedback to the user. 

@Tostino am I understanding correctly that we need to also change the code to add a COMMIT at the end if there are no "BEGIN;" statements in the script?

**Comment by Tostino** [comment]
I'll take a quick demo video from PGAdmin to show how it works there.  PGAdmin is also similar to SSMS (for SQL Server) in how it handles transactions / autocommit.  

To me, Postage's autocommit on/off seems reversed compared to other tools i've used.

In PGAdmin:
- If autocommit is off, it'll start a transaction, run any queries in that transaction, and keep it open at the end of the run waiting for either more queries or a COMMIT/ROLLBACK (or if the script had a COMMIT/ROLLBACK it will close).
- If autocommit is on, a transaction will be started, all queries will execute in the same transaction, and a COMMIT will be issued at the end, unless your query has a BEGIN, in which case no COMMIT will be issued automatically.

Give me a bit and i'll make a short video with some examples.

**Comment by justintocci** [comment]
No demo needed, I understand. So we basically have it reversed AND confused. I'll come up with a couple test scripts and then get this assigned. Thank you for clearing that up for us.

**Comment by justintocci** [comment]
I think we may be stuck on this until Nunzio gets back, which is around July 11. If I get caught up I'll do it myself but I can't say I expect to be free before then. I know it sucks and I apologize.

**Comment by nunziotocci** [comment]
I'm back, I understand the issue and will get this fixed soon.

**Comment by nunziotocci** [comment]
Ok, I did a little bit of research and I have an amendment to your description of autocommit on (changes in bold:
- A transaction will be started, all queries will execute in the same transaction, and a COMMIT will be issued at the end, unless your query has a**n unmatched** BEGIN **(or a transaction was open before running the script)**,  in which case no COMMIT will be issued automatically.

I also added COMMIT/ROLLBACK buttons to match PGAdmin.

Will be seen in next release.
