### ISSUE TITLE
column width always fit to content

### ISSUE THREAD

**Issue by lpfeup** [workflowproducts/postage#338]
Is it possible to have the width off all columns automatically fit to content?

**Comment by justintocci** [comment]
Actually I think Michael may have done this already. If I recall correctly, he realized the scroll bars were causing a performance bottleneck. 

If I am correct, it will be seen in the next release. As soon as he sees this I'm sure he'll chime in.

**Comment by michaeltocci** [comment]
I have done this. Once the results are displayed in the data grid, the columns are resized to the content that is visible at that time. This will be seen in the next release.

In the meantime, in order to trigger manually resize to content: select some columns, right-click on the header and click "Fit To Content".

Thanks for the feedback!

**Comment by lpfeup** [comment]
Thanks!
