### ISSUE TITLE
Not compatible with debian stretch: compiled against libssl.so.1.0.0

### ISSUE THREAD

**Issue by thoastbrot** [workflowproducts/postage#342]
... and stretch offers 1.0.1 only. 

Could you please annotate your releases? And if time allows, please build a stretch deb.

**Comment by nunziotocci** [comment]
It seems Ubuntu OpenSSL 1.0.2 has the libraries named 1.0.0.
So, I'm going to spend a couple hours an x64 Debian Stretch testing VM, I should have a package for you then.

**Comment by nunziotocci** [comment]
I can't upload it to github because it's too large, but I did get a package for you: https://workflowproducts.com/Postage_3.2.16_amd64.deb.zip
**DISCLAMER**: This says it is 3.2.16 but is a snapshot of master from earlier today! It was thoroughly tested so it should be fine, but please be cautious. 
Let me know when you've downloaded it so I can delete it off of our website.

I'll add Debian to our test routine.

**Comment by thoastbrot** [comment]
thank you!
