### ISSUE TITLE
Pasting into datasheet from Apple Numbers

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#69]
I hand typed three records into Numbers (version 3.6.2) and then copied and pasted them into the Postage (version 2.2.0) datasheet. Each Cell got an extra RETURN at the end that I didn't type into Numbers.

Here's what my test data looked like:
![test-data](https://cloud.githubusercontent.com/assets/10438221/20930778/59ce0db0-bb94-11e6-8ba9-6810ada79d62.png)

When I paste this data into a text editor, this is what I get:
```
test1	asdf3	qwer1
test2	asdf2	qwer2
test3	asdf1	qwer3
```

This is what I get in the datasheet after the paste. Notice the records I pasted (the last three records) have scrollbars on each cell while the first record (which I did not paste) is fine.
![datasheet-result](https://cloud.githubusercontent.com/assets/10438221/20930827/8c94464c-bb94-11e6-862c-3131d2f23481.png)

I'm thinking that Numbers is adding returns in the HTML MIME type of the clipboard, as you could see in the paste to a text editor the text MIME type is correct. If that's the case, we should consider not using the HTML MIME type. We already handle the text MIME type (which is more compatible anyway).

**Comment by justintocci** [comment]
Seems like a bug in your HTML-to-text code, not a problem with numbers. I suspect Excel would do the same.

Look into whether you're using PRE or some other way you're interpreting returns as hard returns. Note that you want to preserve returns in the text, but a return at the end of a field is likely just a soft return in HTML to make it human readable. 

At this time, you may be right about switching to the TEXT mimetype. Whatever is easiest in order to preserve the hard returns.

Later, we'll want to have "paste options" in the "clip options" popup that allows you to paste the HTML itself. This would help to preserve other HTML formatting that the user may wish to have such as bold and italics.

**Comment by josephtocci** [comment]
The problem is the newlines in the wrapped around the value in the td tag of the html.

Relevent part of the HTML mimtype clipboard:
````
<td valign="top" style="width: 89.0px; height: 24.0px; border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #000000 #000000 #000000 #000000; padding: 4.0px 4.0px 4.0px 4.0px">
<p style="margin: 0.0px 0.0px 0.0px 0.0px"><font face="Helvetica" size="2" color="#000000" style="font: 10.0px Helvetica; font-kerning: none; font-variant-ligatures: common-ligatures; color: #000000; -webkit-text-stroke: 0px #000000">te<br>
st2</font></p>
</td>
````

**Comment by josephtocci** [comment]
Fixed, if there is a container in a td then use the textcontent of the container instead of the td. Will be seen in next release.

**Comment by justintocci** [comment]
and what if there is more than one container?

**Comment by josephtocci** [comment]
I used trim instead.
