### ISSUE TITLE
Postage Cannot handle comments on columns

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#81]
This is fine:
````
COMMENT ON TABLE schema.table IS 'test table comment';
````
This is not:
````
COMMENT ON COLUMN schema.table.column IS 'test column comment';
````

**Comment by michaeltocci** [comment]
Will be fixed in the next release. The `pg_description` table returned multiple records for a table with column comments and that caused a SQL error `ERROR:  more than one row returned by a subquery used as an expression`. Now, the comments are all added to the table script together.

**Comment by justintocci** [comment]
re-opened due to script not showing column names to re-create comments.

**Comment by michaeltocci** [comment]
![comment-issue](https://cloud.githubusercontent.com/assets/10438221/21159667/ab9c862c-c147-11e6-92f7-1510b34b6269.png)

**Comment by michaeltocci** [comment]
Fixed, will be seen in the next release. The issue was when I previously fixed this code I didn't notice that the column name was missing. I added a `CASE` to the table generation query which conditionally adds the column name if the comment is for a column.

![comment-issue-fix](https://cloud.githubusercontent.com/assets/10438221/21159842/49738fa8-c148-11e6-96fd-29135c7bd2fa.png)
