### ISSUE TITLE
Firefox Dialog missing feature

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#86]
On Chrome, when you press return in a dialog, it presses the default button. On Firefox, it doesn't.

Related to issue #85

**Comment by michaeltocci** [comment]
Fixed.

The issue occurred because Firefox needs custom tag registration to be shimmed. Due to the nature of the shim, the element instantiation is delayed. This delay meant that the buttons you're referring to were not ready to accept focus when the dialog's `after open` callback was run. In browsers where element registration is not shimmed the element instantiation is blocking, so the callback wasn't run until the elements were finished.

To fix this issue I made it so that (on browsers where element registration is shimmed) the dialog waits until the elements in the dialog are instantiated to run the `after open` callback. In browsers where element registration is not shimmed, the code works as it did originally.

Will be seen in next release.
